name: Run Jest Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci  # Install dependencies using npm ci for clean installs

      - name: Ensure execute permissions for Jest
        run: chmod +x node_modules/.bin/jest  # Set execute permissions for Jest

      - name: Run Jest tests
        run: npm test
